routes: 
  - path: /v1/Accommodation*
    service: tourism
  - name: "xyz"
    path: /v2/flat,node/Trafficstation
    service: mobility
    format:
      - property-name: "id"
        property-type: "string"
        property-source: "PointID"